// <auto-generated />
namespace IW5_Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Elephantaddded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Elephantaddded));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191628208_Elephant addded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
