// <auto-generated />
namespace CookBook.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IngredientAmountEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IngredientAmountEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201703060839276_IngredientAmountEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
