<Project Sdk="Microsoft.NET.Sdk">
    
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.JSInterop.WebAssembly" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CookBook.Common.BL\CookBook.Common.BL.csproj" />
    <ProjectReference Include="..\CookBook.Common.Models\CookBook.Common.Models.csproj" />
    <ProjectReference Include="..\CookBook.Web.DAL\CookBook.Web.DAL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="MapperProfiles\" />
  </ItemGroup>

</Project>
