<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AnalysisLevel>preview</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Enums.NET" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CookBook.Api.DAL.Common\CookBook.Api.DAL.Common.csproj" />
    <ProjectReference Include="..\CookBook.Common.BL\CookBook.Common.BL.csproj" />
    <ProjectReference Include="..\CookBook.Common.Models\CookBook.Common.Models.csproj" />
  </ItemGroup>

</Project>
