using System;

namespace CalculatorConsole
{
    partial class Program
    {
        internal class IncorrentCommandLineArguments : ArgumentException
        {
            private string _message;

            public IncorrentCommandLineArguments(string message, CommandLineOptions cmdLineCommandLineOptions) :
                base(message)
            {
                this.CmdLineCommandLineOptions = cmdLineCommandLineOptions;
            }

            /// <summary>
            ///     Property with backing field, may add some inner functionality like input checking
            /// </summary>
            public new string Message
            {
                get { return this._message; }
                set
                {
                    if (value == null)
                    {
                        this._message = string.Empty;
                    }

                    this._message = value;
                }
            }

            /// <summary>
            ///     Auto-implemented property, uses autogenerated backing field
            /// </summary>
            private CommandLineOptions CmdLineCommandLineOptions { get; set; }
        }
    }
}