// <auto-generated />
using System;
using CookBook.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookBook.DAL.Migrations
{
    [DbContext(typeof(CookBookDbContext))]
    [Migration("20190103155242_Data seed")]
    partial class Dataseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookBook.DAL.Entities.IngredientAmountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<Guid>("IngredientId");

                    b.Property<Guid>("RecipeId");

                    b.Property<int>("Unit");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientAmounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d2e7873-3e35-4d40-877c-a3d0d78de3c0"),
                            Amount = 0.5,
                            IngredientId = new Guid("5abdfee1-c970-4afd-aff8-aa3cfef8b1ac"),
                            RecipeId = new Guid("cb8db9b3-799c-4ef2-9d85-ce32a9ffa843"),
                            Unit = 1
                        },
                        new
                        {
                            Id = new Guid("2711f535-3566-446c-9ac6-58261efe3fa3"),
                            Amount = 0.29999999999999999,
                            IngredientId = new Guid("83041385-cb60-401b-bf11-cc5ffb8bc570"),
                            RecipeId = new Guid("cb8db9b3-799c-4ef2-9d85-ce32a9ffa843"),
                            Unit = 2
                        },
                        new
                        {
                            Id = new Guid("c8cdbff9-6692-42ad-93aa-69cb56f95019"),
                            Amount = 5.0,
                            IngredientId = new Guid("cb181669-4e02-449f-bf02-ab6020dfecb4"),
                            RecipeId = new Guid("cb8db9b3-799c-4ef2-9d85-ce32a9ffa843"),
                            Unit = 6
                        },
                        new
                        {
                            Id = new Guid("b417ad46-b94c-487e-8cc1-97ebd7551b13"),
                            Amount = 7.0,
                            IngredientId = new Guid("012ac89a-94e3-4bc2-94b5-c9b05fc83375"),
                            RecipeId = new Guid("cb8db9b3-799c-4ef2-9d85-ce32a9ffa843"),
                            Unit = 4
                        });
                });

            modelBuilder.Entity("CookBook.DAL.Entities.IngredientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5abdfee1-c970-4afd-aff8-aa3cfef8b1ac"),
                            Description = "Tmavá čokoláda s 80% kakaa.",
                            Name = "Tmavá čokoláda"
                        },
                        new
                        {
                            Id = new Guid("83041385-cb60-401b-bf11-cc5ffb8bc570"),
                            Description = "Plnotučné mlieko so 4% tuku.",
                            Name = "Plnotučné mlieko"
                        },
                        new
                        {
                            Id = new Guid("cb181669-4e02-449f-bf02-ab6020dfecb4"),
                            Description = "Najemno umletá mandlová múka",
                            Name = "Mandlová múka"
                        },
                        new
                        {
                            Id = new Guid("012ac89a-94e3-4bc2-94b5-c9b05fc83375"),
                            Description = "Slepačie vajíčko.",
                            Name = "Vajíčko"
                        });
                });

            modelBuilder.Entity("CookBook.DAL.Entities.RecipeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<TimeSpan>("Duration");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb8db9b3-799c-4ef2-9d85-ce32a9ffa843"),
                            Description = "Hovězí maso dobře nasolíme a obalíme v zázvoru, pak v hladké mouce a necháme asi hodinu odležet. V hrnci si osmažíme na pokrájeném špeku s trochou oleje cibuli dosklovata. Pak vložíme hovězí maso, které ze všech stran osmažíme dozlatova. Ke konci smažení přidáme orestovat buď plátky čerstvých hub (200 g) nebo přidáme hrst předem namočených sušených hub a vše zalijeme vývarem nebo vodou s kostkou bujonu. Dusíme pod poklicí, než bude maso měkké, dle potřeby podléváme a občas maso otočíme.",
                            Duration = new TimeSpan(0, 0, 30, 0, 0),
                            Name = "Čokoládová torta",
                            Type = 2
                        });
                });

            modelBuilder.Entity("CookBook.DAL.Entities.IngredientAmountEntity", b =>
                {
                    b.HasOne("CookBook.DAL.Entities.IngredientEntity", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookBook.DAL.Entities.RecipeEntity", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
